# Generated by Django 4.2 on 2023-06-11 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_spacial_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='spacial_user',
        ),
        migrations.AddField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 11, 16, 22, 53, 889332, tzinfo=datetime.timezone.utc), verbose_name='تاریخ انقضای اشتراک ویژه'),
        ),
    ]
