# Generated by Django 4.2 on 2023-06-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_spacial',
            field=models.BooleanField(default=False, verbose_name='مقاله ویژه'),
        ),
    ]
