# Generated by Django 4.2 on 2023-06-11 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_is_spacial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_spacial',
            new_name='is_special',
        ),
    ]
